### ISSUE TITLE
What is the difference between `MMBench test`, `MMBench dev`, `MMBench test (CN)`, `MMBench dev (CN)`, `CCBench dev`?

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/MMBench#10]
Thanks for your benchmark and leaderboard, I have a few questions to ask that could not be located in the documentation.

![image](https://github.com/open-compass/MMBench/assets/8592144/af516f25-48a5-47ba-a1cf-aa6f4c2a1b84)
![image](https://github.com/open-compass/MMBench/assets/8592144/bb7488d8-e031-4f40-83c4-d331f2ea7807)

- Is `dev` the training dataset? Then why does `CCBench` not have `test`? 
- The evaluated models in `dev` and `test` are not the same. 
- What is CCBench, and how does differ from MMBench (CN)? 

@tonysy @gaotongxiao @YuanLiuuuuuu @kennymckormick

**Comment by kennymckormick** [comment]
1.  `dev` means for development usage, with the groundtruth answers released. For the `test` set, the groundtruth answers are confidential. 
2. That's due to some legacy issues. For some models, the model author just provide the `dev` or `test` inference result to use. Thus 
the evaluated models in dev and test are not the same (but that can be special cases).
3. MMBench (CN) is the Chinese translation of MMBench, while CCBench is another set of testing questions focusing on Chinese culture.

**Comment by zhimin-z** [comment]
Thanks for your replies!
If that is the case, why CCBench does not have `test`?

**Comment by kennymckormick** [comment]
CCBench is just a small-scale benchmark for developing purpose, it's not designed to be an official benchmark with `test` split.
