### ISSUE TITLE
About the number of dataset.

### ISSUE THREAD

**Issue by zhouqiji** [open-compass/MMBench#31]
Thanks for your response.
The repo shows that there are #1164 and #1784 questions for dev and test, respectively.
However, the downloaded file contains over 4000 and 10000 data instances for the dev and test.

If I want to submit the test result, should I evaluate all the 1W+ questions?

**Comment by kennymckormick** [comment]
Hi, @zhouqiji ,
The file contains ~10k questions because we use CircularEval: each question may correspond to up to 4 lines in the TSV file.
If you want to submit the test result, you should evaluate all the 6k (v1.0 test) / 7k (v1.1 test) questions respectively. We don't have released files with 10k questions.
